/*
NAVICAT MYSQL DATA TRANSFER

SOURCE SERVER         : 192.168.3.210
SOURCE SERVER VERSION : 50723
SOURCE HOST           : 192.168.3.210:3306
SOURCE DATABASE       : INTERFACE_ONE

TARGET SERVER TYPE    : MYSQL
TARGET SERVER VERSION : 50723
FILE ENCODING         : 65001

DATE: 2018-10-15 11:49:46
*/

CREATE DATABASE `interface_one` DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE interface_one;

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR INTERFACEONE_BANK_CARD
-- ----------------------------
DROP TABLE IF EXISTS `interfaceone_bank_card`;
CREATE TABLE `interfaceone_bank_card` (
  `PHONE` VARCHAR(255) DEFAULT NULL    COMMENT '手机号' ,
  `ID_CARD` VARCHAR(255) DEFAULT NULL    COMMENT '身份证号' ,
  `CARDHOLDER_NAME` VARCHAR(255) DEFAULT NULL    COMMENT '持卡人姓名' ,
  `BANK_NAME` VARCHAR(255) DEFAULT NULL    COMMENT '银行卡归属' ,
  `BANK_CARD_NUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '银行卡号' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8  COMMENT = '银行卡信息表';
ALTER TABLE interfaceone_bank_card COMMENT '银行卡信息表';
-- ----------------------------
-- TABLE STRUCTURE FOR INTERFACEONE_USER
-- ----------------------------
DROP TABLE IF EXISTS `interfaceone_user`;
CREATE TABLE `interfaceone_user` (
  `PASSWD` VARCHAR(255) DEFAULT NULL    COMMENT '密码' ,
  `USER_NAME` VARCHAR(255) DEFAULT NULL    COMMENT '用户姓名' ,
  `ID_CARD` VARCHAR(18) DEFAULT NULL    COMMENT '身份证号' ,
  `PHONE` VARCHAR(255) DEFAULT NULL    COMMENT '手机号' ,
  `BALANCE` DOUBLE(18,2) DEFAULT '0.00'    COMMENT '余额' ,
  `PAYMENT_PASSWORD` VARCHAR(255) DEFAULT NULL    COMMENT '支付密码' ,
  `CURRENTUNIX` BIGINT(20) DEFAULT NULL    COMMENT '当前时间' ,
  `STRUUID` VARCHAR(255) DEFAULT NULL    COMMENT 'token' ,
  `CERTIFICATIONCODE` INT(11) DEFAULT '0'    COMMENT '身份证绑定状态' ,
  `CERTIFICATIONNUMBER` INT(11) DEFAULT '0'    COMMENT '身份证绑定次数' ,
  `CERTIFICATIONTIME` BIGINT(20) DEFAULT NULL   COMMENT '身份证绑定操作时间' ,
  `CERTIFICATIONUUIDTIME` BIGINT(20) DEFAULT NULL    COMMENT 'token最后一次操作时间' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '用户信息表 ';
ALTER TABLE interfaceone_user COMMENT '用户信息表';
-- ----------------------------
-- TABLE STRUCTURE FOR INVESTMENT_PROJECT
-- ----------------------------
DROP TABLE IF EXISTS `investment_project`;
CREATE TABLE `investment_project` (
  `INVESTMENTID` VARCHAR(255) NOT NULL   COMMENT '投资ID' ,
  `INVESTMENTAMOUNT` DOUBLE DEFAULT NULL    COMMENT '投资金额' ,
  `INVESTMENTSERIALNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '投资流水号' ,
  `INVESTMENTPROJECTID` VARCHAR(255) DEFAULT NULL    COMMENT '投资项目ID' ,
  `LINKEDACCOUNT` VARCHAR(255) DEFAULT NULL    COMMENT '关联账户' ,
  `INVESTMENTTIME` BIGINT(20) DEFAULT NULL    COMMENT '投资时间' ,
  `BIDDINGSTATUS` INT(11) DEFAULT NULL    COMMENT '投标状态' ,
  PRIMARY KEY (`INVESTMENTID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '投资项目表 ';
ALTER TABLE investment_project COMMENT '投资项目表';
-- ----------------------------
-- TABLE STRUCTURE FOR PROJECT
-- ----------------------------
DROP TABLE IF EXISTS `project`;
CREATE TABLE `project` (
  `PROJECTNAME` VARCHAR(255) DEFAULT NULL    COMMENT '项目名称' ,
  `PROJECTID` VARCHAR(255) DEFAULT NULL    COMMENT '项目id' ,
  `TOTALPROJECT` DOUBLE DEFAULT NULL    COMMENT '项目金额' ,
  `REMAININGAMOUNT` DOUBLE DEFAULT NULL    COMMENT '剩余额度' ,
  `PROJECTDEADLINE` VARCHAR(255) DEFAULT NULL    COMMENT '项目期限' ,
  `ANNUALINTERESTRATE` DOUBLE DEFAULT NULL    COMMENT '年利率' ,
  `EXTRAINTERESTRATE` DOUBLE DEFAULT NULL    COMMENT '额外利率' ,
  `VALIDITYPERIOD` VARCHAR(255) DEFAULT NULL    COMMENT '有效期' ,
  `RELEASETIME` BIGINT(20) DEFAULT NULL    COMMENT '发布时间' ,
  `ENTRYTIME` BIGINT(20) DEFAULT NULL    COMMENT '录入时间' ,
  `PROJECTSTATUS` BIGINT(20) DEFAULT NULL    COMMENT '项目状态 0为开始回款，4为已回款结束，其中1为未开始回款，' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '项目表 ';
ALTER TABLE project COMMENT '项目表';
-- ----------------------------
-- TABLE STRUCTURE FOR PROJECTRETURNLOG
-- ----------------------------
DROP TABLE IF EXISTS `projectreturnlog`;
CREATE TABLE `projectreturnlog` (
  `SERIALNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '流水号' ,
  `TRANSACTIONTIME` VARCHAR(255) DEFAULT NULL    COMMENT '交易时间' ,
  `BANKCARDNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '银行卡号' ,
  `AMOUNTOFTHETRANSACTION` VARCHAR(255) DEFAULT NULL    COMMENT '交易金额' ,
  `ORDERNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '订单号' ,
  `TRADINGSTATUS` INT(11) DEFAULT NULL    COMMENT '交易状态 0交易失败 1交易成功' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '金额变动表 ';
ALTER TABLE projectreturnlog COMMENT '金额变动表';
-- ----------------------------
-- TABLE STRUCTURE FOR RECHARGEWATER
-- ----------------------------
DROP TABLE IF EXISTS `rechargewater`;
CREATE TABLE `rechargewater` (
  `PHONE` VARCHAR(255) DEFAULT NULL    COMMENT '手机号' ,
  `SERIALNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '流水号' ,
  `TRANSACTIONTIME` VARCHAR(255) DEFAULT NULL    COMMENT '交易时间' ,
  `AMOUNTOFTHETRANSACTION` VARCHAR(255) DEFAULT NULL    COMMENT '交易金额' ,
  `TRADINGSTATUS` INT(11) DEFAULT NULL    COMMENT '交易状态 0交易失败 1交易成功' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '平台对接银行交易信息表 ';
ALTER TABLE rechargewater COMMENT '平台对接银行交易信息表';
-- ----------------------------
-- TABLE STRUCTURE FOR TRANSACTIONLOG
-- ----------------------------
DROP TABLE IF EXISTS `transactionlog`;
CREATE TABLE `transactionlog` (
  `SERIALNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '流水号' ,
  `TRANSACTIONTIME` VARCHAR(255) DEFAULT NULL    COMMENT '交易时间' ,
  `BANKCARDNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '银行卡号' ,
  `AMOUNTOFTHETRANSACTION` VARCHAR(255) DEFAULT NULL    COMMENT '交易金额' ,
  `ORDERNUMBER` VARCHAR(255) DEFAULT NULL    COMMENT '订单号' ,
  `TRADINGSTATUS` INT(11) DEFAULT NULL    COMMENT '交易状态 0交易失败 1交易成功' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '银行对接客户方充值日志信息表 ';
ALTER TABLE transactionlog COMMENT '银行对接客户方充值日志信息表';
-- ----------------------------
-- TABLE STRUCTURE FOR USER_LOGIN
-- ----------------------------
DROP TABLE IF EXISTS `user_login`;
CREATE TABLE `user_login` (
  `SMSVERIFICATIONCODE` VARCHAR(255) DEFAULT NULL    COMMENT '短信验证码' ,
  `CURRENTUNIX` BIGINT(20) DEFAULT NULL    COMMENT '当前系统的时间戳' ,
  `NUMBER` INT(255) DEFAULT NULL    COMMENT '验证码获取次数' ,
  `PHONE` VARCHAR(255) DEFAULT NULL    COMMENT '手机号' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT = '短信验证码数据存储表 ';
ALTER TABLE user_login COMMENT '短信验证码数据存储表';